### ISSUE TITLE
TenDRA build doesn't work when un-tarred into CE

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/misc-builder#3]
I built tendra (huge thanks to @partouf and @katef); but the resulting "obj" directory doesn't seem "portable".

We currently assume we can build compilers in one spot and then untar them elsewhere. To test whether we had a viable binary I built in docker, tar'd and uploaded to s3, then pulled down on one of the CE nodes and tried to run:

```
$ cd tendra-trunk-20200813/
$ ./bin/tcc
tcc: Warning: Can't open environment, 'base': Permission denied
tcc: Warning: Can't open environment, 'base': Permission denied
tcc: Warning: Can't find environment, 'base'
tcc: Fatal: No input files specified
$ cat > ../hellow.c
#include <stdio.h>
int main(int argc, const char *argv[]) { puts("hello\n"); }
$ ./bin/tcc -E /tmp/hellow.c 
tcc: Warning: Can't open environment, 'base': Permission denied
tcc: Warning: Can't open environment, 'base': Permission denied
tcc: Warning: Can't find environment, 'base'
tcc: Fatal: Undefined variable <MKDIR>
```

Any ideas?

**Comment by partouf** [comment]
I'm getting we need to put this somewhere? https://github.com/tendra/tendra/blob/c8780bd250b38dffe840c1afab7912f43c2a50f7/tcc/env/base

**Comment by partouf** [comment]
Or maybe even both startup and env folders https://github.com/tendra/tendra/tree/main/tcc
Why they were not packaged, I'm not sure.

**Comment by partouf** [comment]
Ok, so I've built tendra with these changes to its source code: https://github.com/tendra/tendra/compare/main...partouf:envfixes

And then I could do this and get an executable:
`TEMP_PATH=/tmp TCCENV=/home/partouf/Documents/misc-builder/tendra-trunk-20200813/tendra-trunk-20200813/lib/tcc/env bin/tcc /home/partouf/Documents/main.c
`

The TCCENV bit should probably still be fixed.
And I think this should still be compatible with how other users would build it.

**Comment by partouf** [comment]
need for TCCENV eliminated, sent a PR

**Comment by katef** [comment]
Hi there! These paths are currently compiled into tcc at build time. They can be overridden at runtime of course, see `tcc -vd` to print a list of its internal environment variables. `ENVPATH` is one of those, it's like $PATH for binaries.

So for our purposes for CE, I don't think we _need_ to change anything - we should be able to invoke tcc with something like `tcc -yENVPATH=/path/to/environments ...` to the same effect.

The idea for having tcc figure out its location to set defaults makes sense to me - I'll comment about that on the PR in the tendra repo. Essentially I wonder if we can do the prefixing in the environment files (which are a simple config language), rather than in C.
